pub mod cc;
pub mod coherence;
pub mod cp;
pub mod email;
pub mod hash_format;
pub mod iban;
pub mod json;
pub mod mime;
pub mod nif;
pub mod niss;
pub mod phone;
pub mod range;
pub mod semver;
pub mod string;
pub mod uuid;

pub use cc::{normalize_cc, validate_cc};
pub use coherence::{validate_date_range, validate_datetime_range, validate_state_transition};
pub use cp::{normalize_cp, validate_cp};
pub use email::validate_email;
pub use hash_format::validate_sha256_hex;
pub use iban::{normalize_iban, validate_iban};
pub use json::{require_field, require_object};
pub use mime::validate_mime;
pub use nif::{normalize_nif, validate_nif};
pub use niss::{normalize_niss, validate_niss};
pub use phone::{normalize_phone_pt, validate_phone_pt};
pub use range::validate_in_range;
pub use semver::validate_semver;
pub use string::{max_length, min_length, required};
pub use uuid::validate_uuid;
